---
- name: Playbook_01
  hosts: node1.example.com
  user: ansible
  become: yes
  become_method: sudo
  become_user: root
  
  tasks:
  - name: Add vars
    include_vars:
      file: users.yml

  - name: Create user
    user: 
      name: "{{ item.key }}"
      state: present
      home: /home/{{ item.key }}
      comment: "{{ item.key }}@example.com"
      password: "{{ item.value | password_hash('sha512') }}"
      update_password: on_create
    with_items: "{{ users | dict2items }}"

#  - name: Debug messages
#    debug:
#      msg: "{{ item.key }}"
#      msg: "{{ item.value }}"
#    with_items: "{{ users | dict2items }}"
...
